---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo-exporter
  name: demo-exporter
  namespace: sharedservices
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-exporter
    spec:
      containers:
        - name: demo-exporter
          image: oliver006/redis_exporter:v0.20.2
          env:
            - name: "REDIS_ADDR"
              value: "demo-redis.services:6379"
          ports:
            - name: exporter
              containerPort: 9121
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 100m
              memory: 500Mi
