---
apiVersion: v1
kind: Service
metadata:
  name: demo-redis
  namespace: services
  labels:
    app: demo-redis
spec:
  ports:
  - port: 6379
    name: client
    nodePort: 32278
  type: NodePort
  selector:
    app: demo-redis